<?php

use App\Ingredient;
use Illuminate\Database\Seeder;

class IngredientTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ingredients = [

            'amarena', //[]
            'anatra',
            'basilico',
            'branzino',
            'burrata',
            'caffè',
            'caramello',
            'ceci',
            'cioccolato',
            'cipolla',
            'cocco',
            'cozze',
            'cremino',
            'fagioli',
            'fior di latte',
            'formaggio',
            'fragola',
            'funghi',
            'gamberetti',
            'gamberoni',
            'gorgonzola',
            'insalata',
            'insalata russa',
            'ketchup',
            'kinder bueno',
            'lattuga',
            'limone',
            'maionese',
            'mandorla',
            'mango',
            'manzo',
            'marmellata',
            'melanzane',
            'melone',
            'mozzarella',
            'mozzarella di bufala',
            'nocciola',
            'noodles',
            'nutella',
            'ostriche',
            'pancetta',
            'panna',
            'parmigiano',
            'patatine',
            'pecorino',
            'peperoncino',
            'peperoni',
            'persico',
            'philadelphia',
            'pistacchio',
            'pollo',
            'pomodoro',
            'porcini',
            'prosciutto cotto',
            'prosciutto crudo',
            'ragù',
            'red velvet',
            'rucola',
            'salame',
            'salame piccante',
            'salamelle',
            'salmone',
            'salsa barbecue',
            'salsa di soia',
            'salsa tartare',
            'salsa teriyaki',
            'sogliola',
            'stracciatella',
            'tiramisu',
            'tofu',
            'tonno',
            'wasabi',
            'wurstel',
            'zenzero'
        ];

        $priceIngredients = [
            0.50,
            2.00,
            0.50,
            3.00,
            2.50,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            2.00,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            1.00,
            1.50,
            2.00,
            0.50,
            3.00,
            3.00,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            0.50,
            3.00,
            0.50,
            1.00,
            0.50,
            1.00,
            1.50,
            0.50,
            1.50,
            1.00,
            4.00,
            1.00,
            1.00,
            0.50,
            2.00,
            1.50,
            0.50,
            1.00,
            3.00,
            0.50,
            0.50,
            1.50,
            1.00,
            1.50,
            1.00,
            1.00,
            1.50,
            1.50,
            1.00,
            1.00,
            1.00,
            1.00,
            1.50,
            0.50,
            0.50,
            0.50,
            0.50,
            1.00,
            0.50,
            0.50,
            1.00,
            1.50,
            1.00,
            0.50,
            0.50
        ];

        for($x = 0; $x < count($ingredients); $x++) {

            $newIngredient = new Ingredient();
            $newIngredient->name = $ingredients[$x];
            $newIngredient->price = $priceIngredients[$x];
            $newIngredient->save();

        }
    }
}
