<?php

use App\Plate;
use Illuminate\Database\Seeder;

class PlateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $namePlates = [
            //user-id 11
            //--antipasti--
            'patatine',
            'dippers',
            'patatine e wurstel',
            'bastincini di mozzarella',
            'alette di pollo',
            'spiedini di pollo',
            //--panini--
            'v-rod',
            'night rod',
            'road king',
            'the scout',
            'california',
            'gold wing',
            'vision',
            'vegas',
            //--bevande--
            'acqua minerale',
            'coca cola',
            'coca cola zero',
            'fanta',
            //--birre--
            'la chouffe',
            'mc chouffe',
            'nastro azzurro',
            'kwak',
            'corona',
            'grimbergen blond',
            'leffe triple',
            //----------
            //user-id 8
            //--antipasti--
            'insalata di mare',
            'insalata di polpo e patate',
            'salmone marinato con agrumi e mandorle tostate',
            'baccalà mantecato su cipolla in agrodolce e pistacchio',
            //--primi piatti--
            'raviolo di burrata pugliese',
            'scialatello all\'astice',
            'pacchero polipetti e pachino',
            'spaghettone aglio olio e peperoncino e gambero crudo',
            //--secondi--
            'grigliata mista',
            'catalana mista di crostacei',
            'tonno alla griglia',
            'polpo croccante, carfciofi e rosmarino',
            //--contorni--
            'verdure grigliate',
            'patate al forno',
            'insalata mista',

            //----------
            //user-id 16
            //--dessert--
            'vaschetta gelato 350gr',
            'vaschetta gelato 500gr',
            'vaschetta gelato 750gr',
            'vaschetta gelato 1000gr',
            'mousse nocciola',
            'mousse pistacchio',
            //torte
            'settemezzo pistacchio',
            'settemezzo nocciola',
            'cassata siciliana',
            //crossaint
            'cornetto vuoto',
            'cornetto cioccolato',
            'cornetto pistacchio',
            'cornetto crema',
            'cornetto crema amarena',
            'brioche vuota',
            'brioche crema',
            'brioche cioccolato',
            

        ];

        $descriptionPlates = [
            //user-id 11
            '',
            '',
            '',
            '5pz',
            '5pz',
            '4pz',
            'crudo, pomodoro, mozzarella',
            'crudo, scamorza affumicata, melanzane, rucola',
            'salsiccia, scamorza affumicata, cipolla, maionese',
            'wurstel, patatine, ketchup, maionese',
            'petto di pollo, lattuga, pomodoro, scamorza, maionese',
            'hamburger 100gr, schiacciata piccante, sottiletta, pomodoro, lattuga',
            'doppio hamburger 100gr, uovo, pancetta, sottiletta, maionese',
            'hamburger 100gr, porchetta, scamorza affumicata, melanzane, tabasco',
            '',
            '33cl',
            '33cl',
            '33cl',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            //user-id 8
            '',
            '',
            '',
            '',
            '',
            '(per 2 persone) mezzo astice o astice intero',
            '',
            '',
            '2 gamberoni, 2 scampi, 1 pezzo di tonno, 1 pezzo di seppia',
            'astice intero, 2 gamberi, 2 scampi con pinzimonio di verdure',
            '',
            '',
            '',
            '',
            '',
            //user-id 16
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
        ];

        $pricePlates = [
            2.50,
            3.50,
            3.50,
            4.50,
            4.00,
            4.00,
            4.00,
            4.00,
            4.50,
            4.50,
            4.00,
            5.00,
            5.00,
            5.50,
            5.00,
            1.00,
            2.00,
            2.00,
            2.00,
            5.00,
            5.00,
            2.50,
            5.00,
            5.00,
            5.00,
            //user-id 8
            15.00,
            18.00,
            13.00,
            12.00,
            15.00,
            40.00,
            14.00,
            16.00,
            20.00,
            40.00,
            18.00,
            18.00,
            5.00,
            4.00,
            4.00,
            //user-id 16
            7.00,
            9.00,
            14.00,
            18.00,
            4.00,
            4.00,
            20.00,
            20.00,
            28.00,
            1.20,
            1.50,
            1.50,
            1.50,
            1.50,
            1.50,
            2.00,
            2.00,

        ];

        $picturePlates = [
            '/image/plates/user-id-11/patatine.jpg',
            '/image/plates/user-id-11/dipper.jpg',
            '/image/plates/user-id-11/patatine-wurstel.jpg',
            '/image/plates/user-id-11/bastoncini-mozzarella.jpg',
            '/image/plates/user-id-11/alette-pollo.jpg',
            '/image/plates/user-id-11/spiedini-pollo.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-3.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/acqua.jpg',
            '/image/plates/user-id-11/cocacola.jpg',
            '/image/plates/user-id-11/cocacola.jpg',
            '/image/plates/user-id-11/fanta.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            //user-id 8
            '/image/plates/user-id-8/insalata-mare.jpg',
            '/image/plates/user-id-8/insalata-mare.jpg',
            '/image/plates/user-id-8/salmone.jpg',
            '/image/plates/user-id-8/baccala-pistacchio.jpg',
            '/image/plates/user-id-8/raviolo-burrata.jpg',
            '/image/plates/user-id-8/spaghetto-astice.jpg',
            '/image/plates/user-id-8/paccheri.jpg',
            '/image/plates/user-id-8/spaghettone.jpg',
            '/image/plates/user-id-8/grigliata-mista.jpg',
            '/image/plates/user-id-8/catalana.jpg',
            '/image/plates/user-id-8/tonno.jpg',
            '/image/plates/user-id-8/polpo.jpg',
            '/image/plates/user-id-8/verdure-grigliate.jpg',
            '/image/plates/user-id-8/patate-forno.jpg',
            '/image/plates/user-id-8/insalata.jpg',
            //user-id 16
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/mousse-nocciola.jpg',
            '/image/plates/user-id-16/mousse-pistacchio.jpg',
            '/image/plates/user-id-16/torta-pistacchio.jpg',
            '/image/plates/user-id-16/torta-nocciola.jpg',
            '/image/plates/user-id-16/cassata.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/brioche.jpg',
            '/image/plates/user-id-16/brioche.jpg',
            '/image/plates/user-id-16/brioche.jpg',
        ];

        $userIDPlates = [
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
        ];

        $categoryIDPlates = [
            3,
            3,
            3,
            3,
            3,
            3,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            3,
            3,
            3,
            3,
            48,
            48,
            48,
            48,
            51,
            51,
            51,
            51,
            12,
            12,
            12,
            16,
            16,
            16,
            16,
            16,
            16,
            58,
            58,
            58,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
        ];

        for ($x = 0; $x < count($namePlates); $x++) {

            $newPlate = new Plate();
            $newPlate->name = $namePlates[$x];
            $newPlate->description = $descriptionPlates[$x];
            $newPlate->price = $pricePlates[$x];
            $newPlate->available = true;
            $newPlate->picture = $picturePlates[$x];
            $newPlate->user_id = $userIDPlates[$x];
            $newPlate->category_id = $categoryIDPlates[$x];
            $newPlate->save();
        }
    }
}
