<?php

use App\Plate;
use Illuminate\Database\Seeder;

class PlateTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $namePlates = [
            //user-id 11
            //--antipasti--
            'patatine',
            'dippers',
            'patatine e wurstel',
            'bastincini di mozzarella',
            'alette di pollo',
            'spiedini di pollo',
            //--panini--
            'v-rod',
            'night rod',
            'road king',
            'the scout',
            'california',
            'gold wing',
            'vision',
            'vegas',
            //--bevande--
            'acqua minerale',
            'coca cola',
            'coca cola zero',
            'fanta',
            //--birre--
            'la chouffe',
            'mc chouffe',
            'nastro azzurro',
            'kwak',
            'corona',
            'grimbergen blond',
            'leffe triple',
            //----------
            //user-id 8
            //--antipasti--
            'insalata di mare',
            'insalata di polpo e patate',
            'salmone marinato con agrumi e mandorle tostate',
            'baccalà mantecato su cipolla in agrodolce e pistacchio',
            //--primi piatti--
            'raviolo di burrata pugliese',
            'scialatello all\'astice',
            'pacchero polipetti e pachino',
            'spaghettone aglio olio e peperoncino e gambero crudo',
            //--secondi--
            'grigliata mista',
            'catalana mista di crostacei',
            'tonno alla griglia',
            'polpo croccante, carfciofi e rosmarino',
            //--contorni--
            'verdure grigliate',
            'patate al forno',
            'insalata mista',

            //----------
            //user-id 16
            //--dessert--
            'vaschetta gelato 350gr',
            'vaschetta gelato 500gr',
            'vaschetta gelato 750gr',
            'vaschetta gelato 1000gr',
            'mousse nocciola',
            'mousse pistacchio',
            //torte
            'settemezzo pistacchio',
            'settemezzo nocciola',
            'cassata siciliana',
            //crossaint
            'cornetto vuoto',
            'cornetto cioccolato',
            'cornetto pistacchio',
            'cornetto crema',
            'cornetto crema amarena',
            'brioche vuota',
            'brioche crema',
            'brioche cioccolato',
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //user id 2 -->
            <!-- //piadine -->
            'La Leggenda',
            'La Belpaese',
            'La Semplice',
            'La Leggerezza',
            'La Provenzale',
            'L\’Estate',
            'Il Mare',
            'La Contadina',
            'La Tifosa',
            'La Golosa',
            'La Regale',
            'La Saporita',
            'La Piccante',
            'La Verdissima',
            'La Caprese',
            'La Primavera',
            <!-- //piadine dolci -->
            'Nutella',
            'Confettura extra di lamponi',
            'Crema Baci Perugina',
            'Crema al cioccolato e granella di Kit Kat',
            'Crema al cioccolato e Smarties',
            'Crema Galak e Smarties',
            'Crema Galak, marmellata di lamponi e mirtilli freschi',
            <!-- //bevande -->
            'Acqua naturale 50cl',
            'Acqua frizzante 50cl',
            'Coca Cola 50cl',
            'Fanta 50cl',
            'Sprite 50cl',
            'Estathè al limone 50cl',
            'Estathè alla pesca 50cl',
            'Birra San Gabriel rossa 33cl',
            'Birra San Gabriel bionda 33cl',
            'Birra Menabrea 33cl',
            'Birra Nastro Azzurro 33cl',
            <!-- // user id 6 -->
            //Antipasti
            'Piatto Misto Vegetariano',
            <!-- // Pesce -->
            'Arancino di riso con pesce',
            'Spaghetti cozze e vongole e prezzemolo',
            'Risotto al nero di seppia',
            'Filetto del pescato del giorno con salsa agrodolce e verdure',
            'Cotolette di sarde fritte',
            'Bruschette con alici',
            'Insalatona con sgombro',
            <!-- //vegetariani -->
            'Linguine con pesto di mandorle e basilico',
            'Falafel di piselli',
            'Nuvolette di verdure fritte',
            'Fiori di zucca fritti',
            <!-- //dolci -->
            'Gelato di riso',
            'Torta di mele',
            'Torta alla crema di mandorle e mirtillo',
            <!-- //bevande -->
            'The beicha 1/4lt',
            'The beicha 1/2lt',
            'Acqua minerale Castello 50cl',
            'Acqua minerale Castello 1lt',
            'Estratto di carote e frutta 250 ml.',
            'Estratto di carote e frutta 500 ml.',
            'Caffè d\'orzo',
            'Tisana limone e zenzero',
            'Tisana tarassaco e spirea',
            'Tisana liquirizia',
            'Camomilla',
            <!-- //user id 12 -->
            <!-- //Antipasti -->
            'Edame',
            'Moyashi',
            'Wakame Suonomono',
            'Spicy Wakame',
            'Gari',
            <!-- //Nigiri -->
            'Sushi Nigiri Sake 6pz',
            'Sushi Nigiri Ebi 6pz',
            'Sushi Nigiri Suzuki 6pz',
            <!-- //Gunkan -->
            'Gunkan Sake 2pz',
            'Gunkan Ebi 2pz',
            'Gunkan Maguro 2pz',
            <!-- //temaki -->
            'Yasai Temaki 1pz',
            'Sake Temaki 1pz',
            <!-- //Hosomaki -->
            'Mix Maki 6pz',
            'Tekka Maki 6pz',
            'Sake Maki 6pz',
            <!-- //Uramaki -->
            'Ura Yasai 6pz',
            'Ura California 6pz',
            'Ura Philadelphia 6pz',
            <!-- //sushi - sashimi - chirashi -->
            'Sushi Sakura',
            'Sushi Take',
            'Sashimi Sake',
            'Sashimi Maguro e Sake',
            'Chirashi Sake Tartare',
            <!-- //menu giapponese -->
            'Sushi Maki A',
            'Sushi Maki B',
            'Sushi Maki C',
            'Sushi Sashimi Maki',
            'Tsunami',
            <!-- //tempura -->
            'Ebi Tempura',
            <!-- //dolci -->
            'Dolcetto di riso',
            'Gelato the verde',
            <!-- //bevande -->
            'Acqua naturale 50cl',
            'Acqua frizzante 50cl',
            'Coca Cola 50cl',
            'Fanta 50cl',
            'Sprite 50cl',
            'The giapponese caldo',
            'The verde',
            'The al Gelsomino',
            'Vino bianco Versus 75cl',
            'Vino bianco Lugana 75cl',
            'Birra Kirin 50cl',
            'Birra Asashi 50cl',
            <!-- //user id 20 -->
            <!-- //dolci -->
            'Camille',
            'Biscotti Grancerale',
            'Cannoli di frolla',
            'Strudel di mele',
            'Plum cake',
            'Biscotti con ricotta e limone',
            'Ricciarelli di Siena',
            'Baci di dama',
            'Ciambella al limone',
            'Torta alle fragole',
            //id-1 Il Ristoro
            'Ossobuco col risotto', 
            'Tortellini in brodo',
            'Bucatini alla gricia', 
            'Agnolotti',
            'Genovese',
            'Canederli',
            'Mandilli de saea',
            'Spaghetti alle vongole',
            'Tagliatelle',
            'Cotoletta',
            'Acqua naturale',
            //id-4 Girotondo di pizza
            'Pizza Salvatore',
            'Pizza Nunzia',
            'Pizza Lorenzo',
            'Pizza Victor',
            'Pizza Doris',
            'Insalatona 1',
            'Insalatona 2',
            'Coccole calde con Nutella',
            'Bomboniera Algida da 6 pz.',
            'Donuts zuccherati',
            'Acqua naturale',
            //id-19 Baan Thai
            'Tod Man Khung',
            'Poh Pia Sod',
            'Kai Satay',
            'Phad Thai',
            'Khao Pad Sapparot',
            'Kang Keaw Wan',
            'Khao Neaow Ma Mamuang',
            'Bua Loi',
            'Crepe Gluay Hoom',
            'Acqua naturale',
        ];

        $descriptionPlates = [
            //user-id 11
            '',
            '',
            '',
            '5pz',
            '5pz',
            '4pz',
            'crudo, pomodoro, mozzarella',
            'crudo, scamorza affumicata, melanzane, rucola',
            'salsiccia, scamorza affumicata, cipolla, maionese',
            'wurstel, patatine, ketchup, maionese',
            'petto di pollo, lattuga, pomodoro, scamorza, maionese',
            'hamburger 100gr, schiacciata piccante, sottiletta, pomodoro, lattuga',
            'doppio hamburger 100gr, uovo, pancetta, sottiletta, maionese',
            'hamburger 100gr, porchetta, scamorza affumicata, melanzane, tabasco',
            '',
            '33cl',
            '33cl',
            '33cl',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            //user-id 8
            '',
            '',
            '',
            '',
            '',
            '(per 2 persone) mezzo astice o astice intero',
            '',
            '',
            '2 gamberoni, 2 scampi, 1 pezzo di tonno, 1 pezzo di seppia',
            'astice intero, 2 gamberi, 2 scampi con pinzimonio di verdure',
            '',
            '',
            '',
            '',
            '',
            //user-id 16
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //user id 2 -->
            <!-- //piadine -->
            'Crudo, Squacquerone, Rucola - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se
            non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default
            sarà la piadina!',
            'Bresaola, Rucola, Grana - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se non
            specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default sarà
            la piadina!',
            'Cotto, Mozzarella, Funghi - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se
            non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default
            sarà la piadina!',
            'Tacchino, Squacquerone, Pomodoro, Lattuga - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o
            kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e
            rotolo! Di Default sarà la piadina!',
            'Tonno, Mozzarella, Pomodoro, Origano, Maionese - Nota bene: nelle note specifica che impasto vuoi tra classico,
            integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra
            piadina e rotolo! Di Default sarà la piadina!',
            'Bresaola, Squacquerone, Zucchine grigliate, Crema all\’aceto balsamico - Nota bene: nelle note specifica che impasto
            vuoi tra classico, integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche
            la forma!!! Tra piadina e rotolo! Di Default sarà la piadina!',
            'Salmone, Provola affumicata, Maionese, Lattuga - Nota bene: nelle note specifica che impasto vuoi tra classico,
            integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra
            piadina e rotolo! Di Default sarà la piadina!',
            'Cotto, Brie, Lattuga - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se non
            specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default sarà
            la piadina!',
            'Salsiccia, Gorgonzola DOP, Peperoni Grigliati, Lattuga - Nota bene: nelle note specifica che impasto vuoi tra classico,
            integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra
            piadina e rotolo! Di Default sarà la piadina!',
            'Crudo, Mozzarella, Gamberetti, Salsa cocktail, Lattuga - Nota bene: nelle note specifica che impasto vuoi tra classico,
            integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra
            piadina e rotolo! Di Default sarà la piadina!',
            'Culatta, Brie, Mix Porcini, Rucola - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut
            bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di
            Default sarà la piadina!',
            'Salame, Squacquerone, Rucola - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se
            non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default
            sarà la piadina!',
            'Spianata calabra, Brie, Rucola - Nota bene: nelle note specifica che impasto vuoi tra classico, integrale o kamut bio.
            Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di
            Default sarà la piadina!',
            'Avocado, Pomodoro, Zucchine grigliate, Lattuga, Crema di carciofi - Nota bene: nelle note specifica che impasto vuoi
            tra classico, integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la
            forma!!! Tra piadina e rotolo! Di Default sarà la piadina!',
            'Mozzarella di bufala campana d.o.p., Zucchine grigliate, Pomodoro, Lattuga, Crema all\’aceto balsamico - Nota bene:
            nelle note specifica che impasto vuoi tra classico, integrale o kamut bio. Se non specificato l\'impasto sarà quello
            classico. E puoi scegliere tra anche la forma!!! Tra piadina e rotolo! Di Default sarà la piadina!',
            'Spinaci, Mozzarella, Grana, Crema all\’aceto balsamico, Noci - Nota bene: nelle note specifica che impasto vuoi tra
            classico, integrale o kamut bio. Se non specificato l\'impasto sarà quello classico. E puoi scegliere tra anche la
            forma!!! Tra piadina e rotolo! Di Default sarà la piadina!',
            <!-- //piadine dolci -->
            '',
            '',
            '',
            '',
            '',
            '',
            <!-- //bevande -->
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            <!-- //user id 6 -->
            <!-- //Antipasti -->
            'Un piatto completo vegano formato da una zuppa e un piatto unico con cereali integrali, verdure di stagione e legumi.',
            <!-- // Pesce -->
            'Arancino di riso con pesce',
            'Spaghetti cozze e vongole e prezzemolo',
            'Risotto al nero di seppia',
            'Filetto del pescato del giorno con salsa agrodolce e verdure',
            'Cotolette di sarde fritte',
            'Bruschette con alici',
            'Insalatona con sgombro',
            <!-- //Vegetariani -->
            'Linguine con pesto di mandorle e basilico',
            'Falafel di piselli',
            'Nuvolette di verdure fritte',
            'Fiori di zucca fritti',
            <!-- //Dolci -->
            'Gelato di riso',
            'Torta di mele',
            'Torta alla crema di mandorle e mirtillo',
            <!-- //Bevande -->
            'The verde tostato',
            'The verde tostato',
            'Naturale o frizzante',
            'Naturale o frizzante',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            <!-- //user id 12 -->
            <!-- //Antipasti -->
            'Fagioli di soia giapponese',
            'Germogli di soia alla piastra',
            'Alghe giapponesi in aceto di riso',
            'Alghe giapponesi agro-piccanti',
            'Zenzero in salamoia',
            <!-- //nigiri -->
            'Nigiri di salmone',
            'Nigiri di gambero cotto',
            'Nigiri di branzino',
            <!-- //gunkan -->
            'Bignè di alga con riso, lemon tartare di salmone, avocado e tobiko',
            'Bignè di alga con riso, lemon tartare di gambero cotto, avocado e tobiko',
            'Bignè di alga con riso, lemon tartare di tonno, avocado e tobiko ',
            <!-- //temaki -->
            'Cono di alga con riso e misto vegetariano',
            'Cono di alga con riso, salmone e avocado',
            <!-- //hosomaki -->
            'Riso, tonno, salmone e cetriolo',
            'Riso e tonno',
            'Riso e salmone',
            <!-- //uramaki -->
            'Riso e misto vegetariano',
            'Riso, salsa di tonno, gamberi* cotti e avocado',
            'Riso, philadelphia, gamberi* cotti e avocado',
            <!-- //sushi - sashimi - chirashi -->
            '9 Nigiri, 3 Hosomaki e 2 Uramaki',
            '7 Nigiri, 3 Hosomaki e 2 Uramaki',
            '10 filetti di salmone crudo',
            '10 filetti di tonno crudo',
            'Riso con salmone tritato, avocado e tobiko',
            <!-- //menu giapponesi -->
            '4 Nigiri, 4 Uramaki',
            '6 Nigiri, 2 Uramaki, 4 Hosomaki',
            '8 Nigiri, 4 Uramaki, 2 Hosomaki ',
            '12 filetti di sashimi misti, 4 Nigiri, 3 Hosomaki',
            '8 Nigiri, 12 Sashimi, 8 Uramaki',
            <!-- //tempura -->
            '3 spiedini di gamberetti alla piastra',
            <!-- //dolci -->
            '',
            '',
            <!-- //bevande -->
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            'Vino bianco secco',
            'Vino bianco secco',
            'Birra lager chiara tipica giapponese',
            'Birra bionda tipica giapponese',
            <!-- //user id 20 -->
            <!-- //dolci -->
            'Senza glutine',
            'Senza glutine',
            'Cannoli di frolla senza burro con crema di ricotta senza glutine',
            'Senza glutine',
            'Plum Cake di grano saraceno con scaglie di cioccolata bianca',
            'Senza glutine',
            'Senza glutine',
            'Senza glutine',
            'Senza glutine',
            'Torta morbida con le fragole senza glutine',
            //id-1 Il Ristoro
            'Sicuramente il piatto più ordinato, parola del Rigolo',
            'Cibo molto comune in tutta Italia. In particolare a Bologna e dintorni',
            'Secondo Checchino dal 1887, Er Faciolaro e altri ristoranti romani, l’antenata dell’amatriciana sarebbe il piatto più richiesto.',
            'Piatto principe del Piemonte, gli agnolotti sono i più richiesti secondo il ristorante Del Cambio di Torino.',
            'Non la focaccia genovese, ma il sugo napoletano a base di stufato di carne con cipolle che cuoce molto lentamente per circa 5-6 ore.',
            'Sono quelle polpette preparate con pane raffermo e speck – ne esistono più versioni – e possono essere servite asciutte o in brodo.',
            'Fazzoletti di “seta” conditi con pesto genovese.',
            'Un must della cucina italiana, specialmente – per ovvi motivi – delle località costiere.',
            'Fatti in casa e mangiati al ristorante, sono fra i piatti più diffusi da Nord a Sud.',
            'Da Nord a Sud è un piatto che soddisfa tutti.',
            'Acqua',
            //id-4 Girotondo di pizza
            'Pomodoro, mozzarella fior di latte, provola affumicata, tritato di bovino, pepe, grana e bufalina centrale e basilico',
            'Pomodoro, mozzarella, stracciatella, pancetta arrotolata, pomodori secchi, bufalina centrale e basilico',
            'Mozzarella fior di latte, insalata, salmone affumicato, zest di limone, olio e.v.o., pepe e basilico',
            'Mozzarella, pomodoro, nduja e gorgonzola',
            'Fior di latte, fesa di tacchino, zucchine marinate, mandorle tostate, glassa balsamica e burratina affumicata al centro, basilico',
            'Mozzarella, polpo, gamberetti, olive, melanzane grigliate e scaglie di grana',
            'Gamberetti, salmone, olive, mozzarelline, tocchetti di pane tostato, noci e scaglie di grana',
            'Dolce al palato e al cuore',
            'Niente da aggiungere',
            'Donut zuccherato',
            'Acqua',
            //id-19 Baan Thai
            'Tortino di gamberi fritto con salsa alle prugne',
            'Involtini di carta di riso con erbe Thailandesi alla piastra servito con salsa piccante',
            'Spiedini di pollo marinati e speziati cotti alla piastra e serviti con salsa di arachidi',
            'Tagliatelle di riso saltate con uovo cipollotto, verdure ed anacardi in salsa al Tamarindo con Gamberi',
            'Riso Thai Jasmine saltato con cutrry giallo, verdure, ananas pollo e anacardi con Pollo',
            'Salsa al curry verde con erbe aromatiche, verdure e bambù servito con riso al vapore con Manzo',
            'Mango e riso glutinoso con latte di cocco',
            'Caramelle di riso glutinoso in latte di cocco',
            'Crepe ripiena alla banana con sciroppo di cacao e panna',
            'Acqua'
        ];

        $pricePlates = [
            2.50,
            3.50,
            3.50,
            4.50,
            4.00,
            4.00,
            4.00,
            4.00,
            4.50,
            4.50,
            4.00,
            5.00,
            5.00,
            5.50,
            5.00,
            1.00,
            2.00,
            2.00,
            2.00,
            5.00,
            5.00,
            2.50,
            5.00,
            5.00,
            5.00,
            //user-id 8
            15.00,
            18.00,
            13.00,
            12.00,
            15.00,
            40.00,
            14.00,
            16.00,
            20.00,
            40.00,
            18.00,
            18.00,
            5.00,
            4.00,
            4.00,
            //user-id 16
            7.00,
            9.00,
            14.00,
            18.00,
            4.00,
            4.00,
            20.00,
            20.00,
            28.00,
            1.20,
            1.50,
            1.50,
            1.50,
            1.50,
            1.50,
            2.00,
            2.00,
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //user id 2 -->
            <!-- //piadine -->
            6.40,
            6.50,
            6.20,
            6.60,
            6.50,
            7.40,
            6.80,
            6.10,
            7.10,
            7.90,
            7.70,
            6.30,
            6.30,
            7.70,
            7.20,
            7.10,
            4.10,
            <!-- //piadine dolci -->
            4.10,
            4.10,
            4.10,
            4.10,
            4.10,
            4.10,
            <!-- //bevande -->
            1.50,
            1.50,
            3.00,
            3.00,
            3.00,
            3.00,
            3.00,
            4.50,
            4.50,
            4.00,
            4.00,
            <!-- //user id 6 -->
            <!-- //antipasti -->
            12.00,
            <!-- //pesce -->
            4.00,
            12.00,
            14.00,
            15.00,
            6.00,
            6.00,
            9.00,
            <!-- //vegetariani -->
            6.00,
            6.00,
            7.00,
            7.00,
            <!-- //dolci -->
            4.00,
            4.00,
            4.50,
            <!-- //bevande -->
            0.50,
            1.00,
            1.50,
            2.00,
            3.50,
            6,00,
            1.00,
            2.50,
            2.50,
            2.50,
            2.50
            <!-- //user id 12 -->
            <!-- //antipasti -->
            4.00,
            4.00,
            4.00,
            4.00,
            4.00,
            <!-- //nigiri -->
            9.00,
            9.00,
            9.00,
            <!-- //gunkan -->
            5.00,
            5.00,
            5.00,
            <!-- //temaki -->
            4.50,
            4.50,
            //hosomaki
            5.00,
            5.00,
            5.00,
            <!-- //uramaki -->
            8.00,
            8.00,
            8.00,
            <!-- //sushi - sashimi - chirashi -->
            15.00,
            13.00,
            14.00,
            18.00,
            14.00,
            <!-- //menu giapponese -->
            9.00,
            13.00,
            15.00,
            18.00,
            35.00,
            <!-- //tempura -->
            9.00,
            //dolci
            4.00,
            4.00,
            <!-- //bevande -->
            1.50,
            1.50,
            2.50,
            2.50,
            2.50,
            3.00,
            3.00,
            3.00,
            12.00,
            18.00,
            5.00,
            5.00,
            <!-- //user id 20 -->
            <!-- //dolci -->
            3.00,
            2.00,
            3.00,
            5.00,
            3.00,
            2.00,
            2.00,
            2.00,
            4.00,
            5.00,
            //id-1 Il Ristoro
            15.00,
            11.50,
            17.00,
            12.30,
            16.00,
            9.00,
            19.00,
            16.50,
            12.00,
            12.00,
            2.00,
            //id-4 Girotondo di pizza
            11.60,
            11.60,
            12.40,
            10.50,
            12.30,
            10.00,
            9.50,
            4.00,
            3.00,
            1.50,
            2.00,
            //id-19 Baan Thai
            6.50,
            5.00,
            5.00,
            12.00,
            7.00,
            10.00,
            6.00,
            5.00,
            5.00,   
            2.00
        ];

        $picturePlates = [
            '/image/plates/user-id-11/patatine.jpg',
            '/image/plates/user-id-11/dipper.jpg',
            '/image/plates/user-id-11/patatine-wurstel.jpg',
            '/image/plates/user-id-11/bastoncini-mozzarella.jpg',
            '/image/plates/user-id-11/alette-pollo.jpg',
            '/image/plates/user-id-11/spiedini-pollo.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-1.jpg',
            '/image/plates/user-id-11/panino-3.jpg',
            '/image/plates/user-id-11/panino-2.jpg',
            '/image/plates/user-id-11/acqua.jpg',
            '/image/plates/user-id-11/cocacola.jpg',
            '/image/plates/user-id-11/cocacola.jpg',
            '/image/plates/user-id-11/fanta.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            '/image/plates/user-id-11/birra.jpg',
            //user-id 8
            '/image/plates/user-id-8/insalata-mare.jpg',
            '/image/plates/user-id-8/insalata-mare.jpg',
            '/image/plates/user-id-8/salmone.jpg',
            '/image/plates/user-id-8/baccala-pistacchio.jpg',
            '/image/plates/user-id-8/raviolo-burrata.jpg',
            '/image/plates/user-id-8/spaghetto-astice.jpg',
            '/image/plates/user-id-8/paccheri.jpg',
            '/image/plates/user-id-8/spaghettone.jpg',
            '/image/plates/user-id-8/grigliata-mista.jpg',
            '/image/plates/user-id-8/catalana.jpg',
            '/image/plates/user-id-8/tonno.jpg',
            '/image/plates/user-id-8/polpo.jpg',
            '/image/plates/user-id-8/verdure-grigliate.jpg',
            '/image/plates/user-id-8/patate-forno.jpg',
            '/image/plates/user-id-8/insalata.jpg',
            //user-id 16
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/vaschetta-gelato.jpg',
            '/image/plates/user-id-16/mousse-nocciola.jpg',
            '/image/plates/user-id-16/mousse-pistacchio.jpg',
            '/image/plates/user-id-16/torta-pistacchio.jpg',
            '/image/plates/user-id-16/torta-nocciola.jpg',
            '/image/plates/user-id-16/cassata.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/cornetto.jpg',
            '/image/plates/user-id-16/brioche.jpg',
            '/image/plates/user-id-16/brioche.jpg',
            '/image/plates/user-id-16/brioche.jpg',
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //user id 2 -->
            <!-- //piadine -->
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            '/image/plates/user-id-2/piadina_default.jpg',
            <!-- //piadine dolci -->
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            '/image/plates/user-id-2/piadina_dolce.jpg',
            <!-- //bevande -->
            '/image/plates/user-id-2/acquan.jpeg',
            '/image/plates/user-id-2/acqua.jpg',
            '/image/plates/user-id-2/cocacola.jpg',
            '/image/plates/user-id-2/fanta.jpg',
            '/image/plates/user-id-2/sprite.jpg',
            '/image/plates/user-id-2/estathe.png',
            '/image/plates/user-id-2/estathe.png',
            '/image/plates/user-id-2/birra0.jpg',
            '/image/plates/user-id-2/birra0.jpg',
            '/image/plates/user-id-2/birra1.jpg',
            '/image/plates/user-id-2/birra2.jpg',
            <!-- //user id 6 -->
            <!-- //Antipasti -->
            '/image/plates/user-id-6/piatto_misto_vegetariano.jpg',
            <!-- // Pesce -->
            '/image/plates/user-id-6/arancino_riso_pesce.jpg',
            '/image/plates/user-id-6/spaghetti_cozze_vongole.jpg',
            '/image/plates/user-id-6/risotto_nero_seppia.jpg',
            '/image/plates/user-id-6/filetto_pescato_salsa_agrodolce.jpg',
            '/image/plates/user-id-6/cotolette_sarde_fritte.jpg',
            '/image/plates/user-id-6/brushette_alici.jpg',
            '/image/plates/user-id-6/insalatona_sgombro.jpg',
            <!-- //Vegetariani -->
            '/image/plates/user-id-6/linguine_pesto_mandorle.jpg',
            '/image/plates/user-id-6/falafel_piselli.jpg',
            '/image/plates/user-id-6/nuvolette_verdure_fritte.jpg',
            '/image/plates/user-id-6/fiori_zucca_fritti.jpg',
            <!-- //Dolci -->
            '/image/plates/user-id-6/gelato_riso.jpg',
            '/image/plates/user-id-6/torta_mele.jpg',
            '/image/plates/user-id-6/torta_mandorle_mirtillo.jpg',
            <!-- //Bevande -->
            '/image/plates/user-id-6/the_bancha.jpg',
            '/image/plates/user-id-6/the_bancha.jpg',
            '/image/plates/user-id-6/acqua_castello.jpg',
            '/image/plates/user-id-6/acqua_castello.jpg',
            '/image/plates/user-id-6/estratto_carote_frutta.jpg',
            '/image/plates/user-id-6/estratto_carote_frutta.jpg',
            '/image/plates/user-id-6/caffe_orzo.jpg',
            '/image/plates/user-id-6/the_bancha.jpg',
            '/image/plates/user-id-6/the_bancha.jpg',
            '/image/plates/user-id-6/the_bancha.jpg',
            '/image/plates/user-id-6/the_bancha.jpg',
            <!-- //user id 12 -->
            <!-- //Antipasti -->
            '/image/plates/user-id-12/edame.jpg',
            '/image/plates/user-id-12/moyashi.jpg',
            '/image/plates/user-id-12/wakame_suonomono.jpg',
            '/image/plates/user-id-12/spicy_wakame.jpg',
            '/image/plates/user-id-12/gari.jpg',
            <!-- //Nigiri -->
            '/image/plates/user-id-12/nigiri_sake.jpg',
            '/image/plates/user-id-12/nigiri_ebi.jpg',
            '/image/plates/user-id-12/suzuki.jpg',
            <!-- //Gunkan -->
            '/image/plates/user-id-12/gunkan_sake.jpg',
            '/image/plates/user-id-12/gunkan_ebi.jpg',
            '/image/plates/user-id-12/gunkan_maguro.jpg',
            <!-- //temaki -->
            '/image/plates/user-id-12/temaki_yasai.jpg',
            '/image/plates/user-id-12/temaki_sake.jpg',
            <!-- //Hosomaki -->
            '/image/plates/user-id-12/hosomaki_mix_maki.jpg',
            '/image/plates/user-id-12/hosomaki_tekka_maki.jpg',
            '/image/plates/user-id-12/hosomaki_sake_maki.jpg',
            <!-- //Uramaki -->
            '/image/plates/user-id-12/ura_yasai.jpg',
            '/image/plates/user-id-12/uramaki_ura_california.jpg',
            '/image/plates/user-id-12/uramaki_ura_philadelphia.jpg',
            <!-- //sushi - sashimi - chirashi -->
            '/image/plates/user-id-12/sushi_default.jpg',
            '/image/plates/user-id-12/sushi_default.jpg',
            '/image/plates/user-id-12/sashimi_default.jpg',
            '/image/plates/user-id-12/sashimi_default.jpg',
            '/image/plates/user-id-12/chirashi_default.jpg',
            <!-- //menu giapponese -->
            '/image/plates/user-id-12/sushi_maki_a.jpg',
            '/image/plates/user-id-12/sushi_maki_b.jpg',
            '/image/plates/user-id-12/sushi_maki_c.jpg',
            '/image/plates/user-id-12/sushi_sashimi_maki.jpg',
            '/image/plates/user-id-12/menu_sushi_tsunami.jpg',
            <!-- //tempura -->
            '/image/plates/user-id-12/tempura.jpg',
            <!-- //dolci -->
            '/image/plates/user-id-12/dolce_riso.jpg',
            '/image/plates/user-id-12/gelato_the_verde.jpg',
            <!-- //bevande -->
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            '/image/plates/user-id-12/bevande_default.jpg',
            <!-- //user id 20 -->
            <!-- //dolci -->
            '/image/plates/user-id-20/camille.jpeg',
            '/image/plates/user-id-20/grancereale.jpeg',
            '/image/plates/user-id-20/cannoli.jpeg',
            '/image/plates/user-id-20/strudel.jpg',
            '/image/plates/user-id-20/plumcake.jpg',
            '/image/plates/user-id-20/biscotti_limone.jpg',
            '/image/plates/user-id-20/ricciarelli.jpg',
            '/image/plates/user-id-20/baci.jpg',
            '/image/plates/user-id-20/ciambella.jpg',
            '/image/plates/user-id-20/torta_fragola.jpg',
            //id-1 Il Ristoro
            '/image/plates/user-id-1/1ossobuco.jpg',
            '/image/plates/user-id-1/2tortellini.jpg',    
            '/image/plates/user-id-1/3bucatini.jpg', 
            '/image/plates/user-id-1/4agnolotti.jpg',    
            '/image/plates/user-id-1/5genovese.jpg',  
            '/image/plates/user-id-1/6canederli.jpg',    
            '/image/plates/user-id-1/7mandilli.jpg',    
            '/image/plates/user-id-1/8spaghetti.jpg',    
            '/image/plates/user-id-1/9tagliatelle.jpg',    
            '/image/plates/user-id-1/10cotoletta.jpg',    
            '/image/plates/user-id-1/0acqua.jpg', 
            //id-4 Girotondo di pizza
            '/image/plates/user-id-1/1pizza-salvatore.jpg',    
            '/image/plates/user-id-1/2pizza-nunzia.jpeg', 
            '/image/plates/user-id-1/3pizza-lorenzo.jpeg',    
            '/image/plates/user-id-1/4pizza-victor.jpg', 
            '/image/plates/user-id-1/5pizza-doris.jpg',    
            '/image/plates/user-id-1/6ins1.jpg',    
            '/image/plates/user-id-1/7ins2.jpg',   
            '/image/plates/user-id-1/8coccole-calde.jpeg',    
            '/image/plates/user-id-1/9bomboniera-algida.jpeg',    
            '/image/plates/user-id-1/10donut-zuccherato.jpeg',  
            '/image/plates/user-id-1/0acqua.jpg',   
            //id-19 Baan Thai
            '/image/plates/user-id-1/1tod-man-kung.jpg',    
            '/image/plates/user-id-1/2bambubox.jpg',    
            '/image/plates/user-id-1/3satay.jpg',    
            '/image/plates/user-id-1/4Pad-Thai.jpg',    
            '/image/plates/user-id-1/5khao-pad-sapparot.jpg',    
            '/image/plates/user-id-1/6kang-keaw-wan.jpeg',    
            '/image/plates/user-id-1/7Khao_Niaow_Ma_Muang.jpg',    
            '/image/plates/user-id-1/8bua-loi-Thuai.jpg',    
            '/image/plates/user-id-1/9fried-banana-pancake.jpg',    
            '/image/plates/user-id-1/0acqua.jpg', 
        ];

        $userIDPlates = [
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            11,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            8,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //user id 2 -->
            <!-- //piadine -->
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            <!-- //piadine dolci -->
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            <!-- //bevande -->
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            2,
            <!-- // user id 6 -->
            <!-- //Antipasti -->
            6,
            <!-- // Pesce -->
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            <!-- //vegetariani -->
            6,
            6,
            6,
            6,
            <!-- //dolci -->
            6,
            6,
            6,
            <!-- //bevande -->
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            6,
            <!-- //user id 12 -->
            <!-- //Antipasti -->
            12,
            12,
            12,
            12,
            12,
            <!-- //Nigiri -->
            12,
            12,
            12,
            <!-- //Gunkan -->
            12,
            12,
            12,
            <!-- //temaki -->
            12,
            12,
            <!-- //Hosomaki -->
            12,
            12,
            12,
            <!-- //Uramaki -->
            12,
            12,
            12,
            <!-- //sushi - sashimi - chirashi -->
            12,
            12,
            12,
            12,
            12,
            <!-- //menu giapponese -->
            12,
            12,
            12,
            12,
            12,
            <!-- //tempura -->
            12,
            <!-- //dolci -->
            12,
            12,
            <!-- //bevande -->
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            12,
            <!-- //user id 20 -->
            <!-- //dolci -->
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            20,
            //id-1 Il Ristoro
            1,
            1,
            1,
            1,
            1,    
            1,
            1,
            1,
            1,
            1,
            1,
            //id-4 Girotondo di pizza
            4,
            4,
            4,
            4,
            4,    
            4,
            4,
            4,
            4,
            4,
            4,
            //id-19 Baan Thai
            19,
            19,
            19,
            19,
            19,    
            19,
            19,
            19,
            19,
            19,
        ];

        $categoryIDPlates = [
            3,
            3,
            3,
            3,
            3,
            3,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            43,
            4,
            4,
            4,
            4,
            5,
            5,
            5,
            5,
            5,
            5,
            5,
            3,
            3,
            3,
            3,
            48,
            48,
            48,
            48,
            51,
            51,
            51,
            51,
            12,
            12,
            12,
            16,
            16,
            16,
            16,
            16,
            16,
            58,
            58,
            58,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            14,
            //Ristoranti: Piadineria, Sweet and Fit, Primo sushi, Yum - Sam
            <!-- //piadine -->
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            <!-- //piadine dolci -->
            45,
            45,
            45,
            45,
            45,
            45,
            45,
            <!-- //bevande -->
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            <!-- // user id 6 -->
            <!-- //Antipasti -->
            3,
            <!-- // Pesce -->
            44,
            44,
            44,
            44,
            44,
            44,
            44,
            <!-- //vegetariani -->
            15,
            15,
            15,
            15,
            <!-- //dolci -->
            16,
            16,
            16,
            <!-- //bevande -->
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            <!-- //user id 12 -->
            <!-- //Antipasti -->
            3,
            3,
            3,
            3,
            3,
            <!-- //Nigiri -->
            40,
            40,
            40,
            <!-- //Gunkan -->
            19,
            19,
            19,
            <!-- //temaki -->
            56,
            56,
            <!-- //Hosomaki -->
            21,
            21,
            21,
            <!-- //Uramaki -->
            59,
            59,
            59,
            <!-- //sushi - sashimi - chirashi -->
            53,
            53,
            50,
            50,
            10,
            <!-- //menu giapponese -->
            30,
            30,
            30,
            30,
            30,
            <!-- //tempura -->
            57,
            <!-- //dolci -->
            16,
            16,
            <!-- //bevande -->
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            4,
            <!-- //user id 20 -->
            <!-- //dolci -->
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            16,
            //id-1 Il Ristoro
            48,
            48,
            48,
            48,
            48,
            12,
            48,
            47,
            48,
            51,
            4,
            //id-4 Girotondo di pizza
            46,
            46,
            46,
            46,
            46,
            22,
            22,
            16,
            16,
            16,
            4,
            //id-19 Baan Thai
            48, 
            51,
            51,
            48,
            62,
            49,
            16,
            16,
            16,
            4
        ];

        for ($x = 0; $x < count($namePlates); $x++) {

            $newPlate = new Plate();
            $newPlate->name = $namePlates[$x];
            $newPlate->description = $descriptionPlates[$x];
            $newPlate->price = $pricePlates[$x];
            $newPlate->available = true;
            $newPlate->picture = $picturePlates[$x];
            $newPlate->user_id = $userIDPlates[$x];
            $newPlate->category_id = $categoryIDPlates[$x];
            $newPlate->save();
        }
    }
}